require: rubocop-rails
inherit_gem:
  rubocop-rails_config:
    - config/rails.yml
  rubocop-discourse:
    - default.yml
AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
